import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import InstagramContact from "./components/InstagramContact";
import Footer from "./components/Footer";
import OurBlog from "./components/OurBlogs";
import NewArrival from "./components/NewArrival";
import TopPicks from "./components/TopPicks";
import FeaturedProducts from "./components/FeaturedProduct";
import HeroSection from "./components/HeroSection";
import Navbar from "./components/Navbar";
import { HeaderMain } from "./components/HeaderMain";
import HeaderTop from "./components/HeaderTop";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <HeaderTop/>
        <HeaderMain/>
        <Navbar/>
        <HeroSection/>
        <FeaturedProducts/>
        <TopPicks/>
        <NewArrival/>
        <OurBlog/>
        <InstagramContact/>
        <Footer/>
        {children}
      </body>
    </html>
  );
}
